language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - nightly
before-script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit tests/
matrix:
  allow_failures:
    - php: 5.4
  fast_finish: true