sudo: required
dist: trusty
language: php
php:
  - '5.6'
  - '7.0'
before-script:
  - composer install
  - composer update
script:
  - sudo chmod +x ./build/build_script.sh
  - ./build/build_script.sh
matrix:
  fast_finish: true